version: '3.1'
services:
  app:
    container_name: backend
    image: backend:latest
    build: ./backend/disasterresponse
    expose:
      - "4000"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      
  db:
    image: 'postgres:13.1'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      
  frontend_dev:
    container_name: frontend_dev
    build:
      context: ./frontend/disasterresponse
      dockerfile: Dockerfile_dev
    expose:
      - "3000"
    volumes:
      - ./frontend/disasterresponse/node_modules:/app/node_modules
      - frontend_files:/app/build
      - ./frontend/disasterresponse:/app

  webserver:
    image: nginx
    container_name: webserver
    depends_on:
      - app
      - frontend_dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - frontend_files:/var/www:r
      - ./nginx_dev/:/etc/nginx/conf.d/

volumes:
  frontend_files: