version: '3.1'
services:
  backend_dev:
    container_name: backend_dev
    image: backend:latest
    build: ./backend/disasterresponse
    expose:
      - "4000"
    depends_on:
      - db_dev
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_dev:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - app_network
  db_dev:
    image: 'postgres:13.1'
    container_name: db_dev
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    networks:
      - app_network

  frontend_dev:
    container_name: frontend_dev
    build:
      context: ./frontend/disasterresponse
      dockerfile: Dockerfile_dev
    expose:
      - "3000"
    volumes:
      - ./frontend/disasterresponse/node_modules:/app/node_modules
      - ./frontend/disasterresponse:/app
    networks:
      - app_network

  webserver_dev:
    image: nginx
    container_name: webserver_dev
    depends_on:
      - backend_dev
      - frontend_dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_dev/:/etc/nginx/conf.d/
    networks:
      - app_network

volumes:
  frontend_files:

networks:
  app_network: