version: '3.1'
services:
  backend:
    container_name: backend
    image: backend:latest
    build: ./backend/disasterresponse
    ports:
      - "4000:4000"
    networks:
      - app_network
    depends_on:
      - postgresqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      
  postgresqldb:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    networks:
      - app_network
  frontend:
    container_name: frontend
    build: ./frontend/disasterresponse
    image: frontend:latest
    ports:
      - "3000:3000"
    networks:
      - app_network
      
networks:
  app_network: