version: '3.1'
services:
  backend:
    container_name: backend
    image: backend:latest
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "8081:8081"
    expose:
      - "8081"
    depends_on:
      - db
    environment:
      - RESQ_APPDIR=/app/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - app_network
      
  db:
    image: 'postgres:13.1'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    networks:
      - app_network
      
networks:
  app_network:
